In [3]:
from bs4 import BeautifulSoup
import requests
import regex as re
import pandas as pd
import numpy as np
from termcolor import colored
from urllib.request import urlopen
import json
pd.set_option('display.max_columns', None)

In [8]:
num_beds = '' # a digit or ''
num_baths = ''
min_price = ''
max_price = ''
available_in = ''
city = 'Calgary'
residence_type = ''
cur_page= '1'


custom_url = f'https://www.rentfaster.ca/api/map.json?currentpage={cur_page}&cities={city}&price_range_adv[from]=null&price_range_adv[to]=null'
response = urlopen(custom_url)
data_json = json.loads(response.read())

listings = data_json['listings']
df = pd.DataFrame(listings)

print('Unique ids = ', (df.id.unique()))
print('Number of unique ids = ', len(df.id.unique()))

if 'search' in data_json.keys(): print('My search = ', data_json['search'])
if 'query' in data_json.keys(): print('My query = ', data_json['query'])

Unique ids =  [377368  21358 361795 393080 343046 343051 318403 354690 476038 477769
 483743 360258 437507 430647 430648 351340 430315 477784 471183 454527
 434051 393079 422955  21997  22012 462796  19662  20548  21994  19655
  19660  31264  19663 403415  19955  22009 111726 477778 417059 484356
  92378 478962  19666 483457 361659 455899 110575 438172 453317 484202
 378083  71593 146925 453737 483494 422050 484212 481947 484214 340058
 355713  75288 355714 481952 453881 483510  75289 355717 435536 350947
 355718  75880 484232 302656 456421 483902  76227 314015 314173 479453
 449276 480364 117563 483914  78120 480414 483920 484255 484256  78918
 357075 432134 119667 484264 479457 484266 482037 484277 422866 342039
 468634 454769 483951 484289 460983    418 373063 457150 484299  32351
 449970 405788 484307 417750   1528 484311   2243 309609 446350   2244
 439393 461317   2245 482603 298271   2247 383123   2248 436358   2542
 298730 484326   2544 469102 127938 299144   2592 480680 482635   2844
 481481 482137 484346   3408   3474 384259 343049 317519  91435 374359
 318171 482693 482696 482697 482700 343194   5614 474919 375532 465916
 483691 484036 481621 484040 478869 436606 483284 413804 320923 413819
 478921 483295 475072 440277 482760  51405 484070  51406 466381 470158
 480978  51407  99281 359908 466383 473397  99283 359909 473398 483749
 407788 473402  15758 138393 311903 479918 414198 475368 484086 414397
  56399 482839 452039 388740 407850 483371  17744 337415 470326 470380
 480065 408282 470385 347214 420132 322758 105336 140595 305820 484143
 470759  64055 483815 107189 349245 483817 477696 409437  65058 483828
 109509 420759 483454 482342 483461 471341 482377 313092 113896 431016
 115182 478185 149666 478187 453889 446055  31050 464911 483960 309343
 417846 482132 406174 458099 406205 484002 465385 480770 474843 478625
 418065 132584 359371 426105  49304 473054 413950 483753 138524 138783
 466588 484085 481050 484090 484117 105638 305871 481820 479245 484151
 409262 107726]
Number of unique ids =  282
My search =  {'currentpage': '1', 'cities': 'Calgary', 'price_range_adv': {'from': 'null', 'to': 'null'}}

In [20]:
df.loc[40:50]

,ref_id,id,userId,rented,phone,phone_2,email,availability,a,v,f,s,eid,intro,city,community,latitude,longitude,marker,link,thumb2,preferred_contact,type,price,beds,sq_feet,baths,cats,dogs,utilities_included
40,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,1832,none,581,1,2.0,2.0,[Heat]
41,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,1595,none,537,1,2.0,2.0,[Heat]
42,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,1847,none,631,1,2.0,2.0,[Heat]
43,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,1620,none,535,1,2.0,2.0,[Heat]
44,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,2481,none,1106,2,2.0,2.0,[Heat]
45,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,2156,none,900,2,2.0,2.0,[Heat]
46,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,1697,none,576,1,2.0,2.0,[Heat]
47,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,2201,none,890,2,2.0,2.0,[Heat]
48,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,1647,none,541,1,2.0,2.0,[Heat]
49,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,2955,none,1271,2.5,2.0,2.0,[Heat]
50,476038,476038,1252043,Not-Rented,8337718989,,True,Immediate,2000-01-01,1,0,RSYNC,476038,1229 Macleod Trail SE,Calgary,Victoria Park,51.040571,-114.058647,4397ab8cf3e796d141f269ff3edbf4ff,/ab/calgary/rentals/apartment/1-bedroom/victor...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,2775,none,1174,2.5,2.0,2.0,[Heat]

In [26]:
not_a_list = []
for i in range(len(df)):
    try: assert type(df.loc[i,'utilities_included'])==list
    except: not_a_list.append(i)

In [30]:
df.dropna(subset=['sq_feet', 'utilities_included', 'type', 'price'], inplace=True)

In [ ]:
df.fillna(0)

In [31]:
df.loc[:, 'utility_heat'] = df.loc[:, 'utilities_included'].apply(lambda x: 1 if 'Heat' in x else 0)
df.loc[:, 'utility_electricity'] = df.loc[:, 'utilities_included'].apply(lambda x: 1 if 'Electricity' in x else 0)
df.loc[:, 'utility_water'] = df.loc[:, 'utilities_included'].apply(lambda x: 1 if 'Water' in x else 0)
df.loc[:, 'utility_cable'] = df.loc[:, 'utilities_included'].apply(lambda x: 1 if 'Cable' in x else 0)
df.loc[:, 'utility_internet'] = df.loc[:, 'utilities_included'].apply(lambda x: 1 if 'Internet' in x else 0)

In [34]:
df.drop(columns=['utilities_included'], inplace=True)

In [39]:
len(df) == len(df.drop_duplicates())

False

In [42]:
df.drop_duplicates(inplace=True)
df.reset_index(inplace=True)

In [44]:
df.head(1)

,index,ref_id,id,userId,rented,phone,phone_2,email,availability,a,v,f,s,eid,intro,city,community,latitude,longitude,marker,link,thumb2,preferred_contact,type,price,beds,sq_feet,baths,cats,dogs,utility_heat,utility_electricity,utility_water,utility_cable,utility_internet
0,0,377368,377368,25428,Not-Rented,4035080684,,True,Immediate,2000-01-01,1,0,RSYNC,377368,3520 31 St. NW,Calgary,Brentwood,51.084169,-114.128718,00fb1aee1575c135383933289fff598f,/ab/calgary/rentals/apartment/1-bedroom/brentw...,https://f1a3d4fea3a9a877e732-356deb4d9644d2835...,Phone||Text||Email,Apartment,2305,none,527,1,2.0,2.0,1,1,1,0,0

In [47]:
cols_to_drop = ['phone', 'phone_2', 'f', 's',
                'intro', 'userId', 'id', 'ref_id',
                'v', 'thumb2','link', 'marker', 'preferred_contact'
                ]

df.drop(columns=cols_to_drop, inplace=True)

In [45]:
not_int = []
for i in range(len(df)):
    try: int(df.loc[i, 'sq_feet'])
    except: not_int.append(i)

df.drop(not_int, inplace=True)
df.reset_index(inplace=True)

In [48]:
df.fillna(0, inplace=True)

In [ ]:
df.loc[:, 'price'] = df.loc[:, 'price'].apply(lambda x: int(x))

### Practice .1

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/hzjken/SG-rental-analytics/master/code_and_data/model_data.csv'
df = pd.read_csv(url)
df.head()

,area,bedroom,first_i_school_dist,first_mrt_dist,first_p_school_dist,price,psf,sec_i_school_dist,sec_mrt_dist,sec_p_school_dist,...,count,dist_to_shops,dist_to_foodcourt,dist_to_supermarket,dist_to_downtown,apartment,bungalow,condominium,hdb,terrace_house
0,3009,4,0.49,0.57,0.82,5300,1.76,3.86,1.21,1.39,...,1,1.428765,2.134875,0.985758,14.407814,0,0,0,0,1
1,3009,4,0.49,0.57,0.82,5300,1.76,3.86,1.21,1.39,...,1,1.428765,2.134875,0.985758,14.407814,0,0,0,0,1
2,970,2,1.54,0.54,0.80,4000,4.12,1.82,0.61,1.47,...,1,0.633214,0.136767,0.244170,1.716227,0,0,1,0,0
3,1970,2,1.54,0.54,0.80,5200,2.64,1.82,0.61,1.47,...,1,0.633214,0.136767,0.244170,1.716227,0,0,1,0,0
4,1044,2,1.29,0.82,0.37,5500,5.27,1.38,0.98,1.42,...,1,1.057692,0.475773,0.626818,2.198972,1,0,0,0,0

In [3]:
pd.read_json('https://www.rentfaster.ca/api/map.json?e=undefined&beds=&baths=&type=&price_range_adv%5Bfrom%5D=450price_range_adv%5Bfrom%5D=3000&availability=May')

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [ ]:
price_range_adv%5Bto%5D=2300&price_range_adv%5Bfrom%5D=450

In [ ]:
from bs4 import BeautifulSoup
import urllib2
import csv

url = 'https://www.rentfaster.ca//ab/calgary'
html = urllib2.urlopen(url).read()
soup = BeautifulSoup(html)
table = soup.select_one("table.data2_s")
# python3 just use th.text
headers = [th.text.encode("utf-8") for th in table.select("tr th")]

with open("out.csv", "w") as f:
    wr = csv.writer(f)
    wr.writerow(headers)
    wr.writerows([[td.text.encode("utf-8") for td in row.find_all("td")] for row in table.select("tr + tr")])